name: Deploy to gh pages

on:
  push:
    branches: [ "gh-pages" ]

  workflow_dispatch:

jobs:
  deploy:
    environment:
       name: github-pages
       url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
          node-version-file: 'package.json'

    - name: Build
      run:
        npm ci
    - name: Compile Gulp
      run:
        gulp

    # - name: Deploy
    #     uses: JamesIves/github-pages-deploy-action@v4
    #     with:
    #       folder: public
    #       branch: gh-pages
    #       single-commit: true
