name: Deploy to gh pages

on:
  push:
    branches: [ "gh-pages" ]

  workflow_dispatch:

jobs:
  deploy:
    environment:
       name: github-pages
       url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
          node-version: 16.x

    - name: Checkout
      uses: actions/checkout@v3
      with:
        lfs: true

    - name: Build
      run:
        npm install
    - name: Compile Gulp
      run:
        gulp

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: .
        
