name: Deploy to gh pages

on:
  push:
    branches: [ "gh-pages" ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: go
      run: cd Eieny/Eieny.github.io
    - name: Build
      run:
        npm install
    - name: Compile Gulp
      run:
        gulp

    # - name: Deploy
    #     uses: JamesIves/github-pages-deploy-action@v4
    #     with:
    #       folder: public
    #       branch: gh-pages
    #       single-commit: true
